# Install MinerU into a separate Python 3.12 venv (.venv-extract)
# Main project .venv can stay on 3.14; MinerU only supports Python <3.14
# Usage: powershell -ExecutionPolicy Bypass -File scripts/install_extract_deps.ps1

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path $PSScriptRoot -Parent
Set-Location $RepoRoot

$Py312 = $env:KT_PYTHON
if (-not $Py312) {
    foreach ($c in @("E:\Python312\python.exe", "C:\Python312\python.exe")) {
        if (Test-Path $c) { $Py312 = $c; break }
    }
}
if (-not $Py312 -or -not (Test-Path $Py312)) {
    Write-Error @"
Python 3.12/3.13 not found. MinerU does not support Python 3.14+.
Install Python 3.12 to E:\Python312\ or set KT_PYTHON to its python.exe path.
"@
}

$ExtractVenv = Join-Path $RepoRoot ".venv-extract"
$ExtractPy = Join-Path $ExtractVenv "Scripts\python.exe"
$MainPy = Join-Path $RepoRoot ".venv\Scripts\python.exe"
$PipIndex = "https://mirrors.aliyun.com/pypi/simple/"

# ---- Caches on E: (project var/cache) ----
$CacheRoot = Join-Path $RepoRoot "var\cache"
foreach ($d in @(
    "$CacheRoot\pip", "$CacheRoot\huggingface\hub", "$CacheRoot\modelscope",
    "$CacheRoot\mineru\models\pipeline", "$CacheRoot\mineru\models\vlm", "$CacheRoot\tmp"
)) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

$env:PIP_CACHE_DIR = "$CacheRoot\pip"
$env:HF_HOME = "$CacheRoot\huggingface"
$env:HUGGINGFACE_HUB_CACHE = "$CacheRoot\huggingface\hub"
$env:MODELSCOPE_CACHE = "$CacheRoot\modelscope"
$env:MINERU_TOOLS_CONFIG_JSON = "$CacheRoot\mineru\mineru.json"
$env:MINERU_MODEL_SOURCE = "modelscope"
$env:TMP = "$CacheRoot\tmp"
$env:TEMP = "$CacheRoot\tmp"

Write-Host "==> Cache root:     $CacheRoot  (drive $($RepoRoot.Substring(0,2)))"
Write-Host "==> MinerU venv:    $ExtractVenv  (Python 3.12/3.13 only)"
Write-Host "==> Main project:   $MainPy  (unchanged)"

if (-not (Test-Path $ExtractPy)) {
    Write-Host "==> Create .venv-extract with $Py312"
    & $Py312 -m venv $ExtractVenv
}

$ver = & $ExtractPy -c "import sys; print(sys.version_info[:2])"
Write-Host "==> Extract venv Python: $(& $ExtractPy --version)"

Write-Host "==> Install MinerU into .venv-extract"
& $ExtractPy -m pip install -U pip -i $PipIndex
& $ExtractPy -m pip install -U 'mineru[all]' -i $PipIndex

Write-Host "==> Install PyMuPDF into main .venv (PDF fallback)"
if (Test-Path $MainPy) {
    & $MainPy -m pip install -U 'pymupdf>=1.24,<2' -i $PipIndex
} else {
    Write-Host "    (main .venv missing; skip pymupdf — run project setup first)"
}

Write-Host "==> Write MinerU path for kt_workflow"
$MineruExe = Join-Path $ExtractVenv "Scripts\mineru.exe"
$EnvFile = Join-Path $RepoRoot ".env.mineru.local"
@"
# Auto-generated by install_extract_deps.ps1 — source before kt runs or merge into .env
KT_MINERU_PYTHON=$ExtractPy
KT_MINERU_CLI=$MineruExe
KT_CACHE_ON_PROJECT=1
MINERU_MODEL_SOURCE=modelscope
"@ | Set-Content -Encoding UTF8 $EnvFile

Write-Host "==> Verify mineru"
if (Test-Path $MineruExe) {
    & $MineruExe --help | Select-Object -First 5
} else {
    & $ExtractPy -m mineru --help | Select-Object -First 5
}

Write-Host ""
Write-Host "Done. Add to .env (or copy from .env.mineru.local):"
Write-Host "  KT_MINERU_PYTHON=$ExtractPy"
Write-Host "  KT_MINERU_CLI=$MineruExe"
Write-Host "  KT_CACHE_ON_PROJECT=1"
Write-Host "  KT_EXTRACT_BACKEND=auto"
Write-Host "  KT_MINERU_BACKEND=pipeline"
